datasources:
  default:
    url: ${JDBC_DATABASE_URL}
    password: ${JDBC_DATABASE_PASSWORD}
    username: ${JDBC_DATABASE_USERNAME}
    dialect: postgres
    driver-class-name: org.postgresql.Driver

micronaut:
  security:
    intercept-url-map:
    - pattern: /swagger/**
      httpMethod: GET
      access:
      - isAnonymous()
    - pattern: /swagger-ui/**
      httpMethod: GET
      access:
      - isAnonymous()
  application:
    name: NoThanks
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
        enabled: true
#      swagger-ui:
#        paths: classpath:META-INF/swagger/views/swagger-ui
#        mapping: /swagger-ui/**
#        enabled: true

liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.yml'

hibernate:
  hbm2ddl:
    auto: verify